name: pv_neutral_abnahme_protokoll
description: PV-Abnahmeprotokoll mit Spracheingabe, PDF und Fotodokumentation
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # PDF
  pdf: ^3.11.1
  printing: ^5.13.4

  # Speicherorte
  path_provider: ^2.1.4

  # PDF öffnen
  open_filex: ^4.5.0

  # Spracheingabe
  speech_to_text: ^7.0.0

  # Berechtigungen
  permission_handler: ^11.3.1

  # Unterschrift
  signature: ^5.5.0

  # Fotos / Kamera
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true